### ISSUE TITLE
yarn使用http源报错

### ISSUE THREAD

**Issue by jzsn2018** [jzsn2018/day-record#1]
Unsafe http requests must be explicitly whitelisted in your configuration

```yaml
# .yarnrc.yml
npmRegistryServer: "http://artifactory.com/npm/"
unsafeHttpWhitelist: ["artifactory.com"] // 只要配置域名就可以了
```
